---
mysql::prefer_maria_db: false

---
apt::always_apt_update: true
apt::sources:
  'mysql':
    comment: 'This is the official repository for MySQL'
    location: 'http://repo.mysql.com/apt/ubuntu/'
    release: 'trusty'
    repos: 'mysql-5.6'
    key: '5072E1F5'
    key_server: 'pgp.mit.edu'
    include_src: 'true'
    include_deb: 'true'

  'mariadb':
    comment: 'This is the official repository for MariaDB'
    location: 'http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.0/ubuntu'
    release: 'trusty'
    repos: 'main'
    key: '0xcbcb082a1bb943db'
    key_server: 'keyserver.ubuntu.com'
    include_src: true
    include_deb: true

#apt::ppas:
#  'ppa:couchdb/stable': 'ppa:couchdb/stable'

