# By default all services will be installed but only default services will be started on system start.
# Exeption is MariaDB and MySQL, they can not be installed at same time by this way.

---
dbms:
  MySQL:
  ## MySQL and MariaDB can not be installed at same time, therefore one of them must be choosed.
  ## Set to true if you want MariaDB
    prefer_maria_db: true
    install: true
    autostart: true
    root_password: ''

  PostgreSQL:
    version: 9.4
    install: false
    autostart: false
    password: ''

  CouchDB:
    install: false
    autostart: false
    password: ''

  Couchbase:
    install: false
    autostart: false
    password: ''

  MongoDB:
    install: false
    autostart: true
    password: ''

webserver:
  Apache:
    install: true
    autostart: true

  NginX:
    install: false
    autostart: false
    
serversidescripting:
  php:
    default:
      install: true
      autostart: true
      timezone: UTC
      packages:
        - php5
        - php5-common
        - php5-gd
        - php5-mysql
        - php5-imap
        - php5-cli
        - php-pear
        - php-auth
        - php5-mcrypt
        - mcrypt
        - php5-imagick
        - imagemagick
        - php5-curl
        - php5-intl
        - php5-memcache
        - php5-memcached
        - php5-ming
        - php5-ps
        - php5-pspell
#        - php5-recode
        - php5-fpm
        - php5-sqlite
        - php5-tidy
        - php5-xmlrpc
        - php5-xsl
        - memcached
        - libexpat1
        - ssl-cert'
      extensions:
    custom:
      5.5.20:
        install: false
        autostart: false
        extensions:


