# By default all services will be installed but only default services will be started on system start.
# Exeption is MariaDB and MySQL, they can not be installed at same time by this way.

---
dbms:
  MySQL:
  ## MySQL and MariaDB can not be installed at same time, therefore one of them must be choosed.
  ## Set to true if you want MariaDB
    prefer_maria_db: true
    autostart: true
    root_password: ''

  PostgreSQL:
    version: 9.4
    autostart: false
    password: ''

  CouchDB:
    autostart: false
    password: ''

  Couchbase:
    autostart: false
    password: ''

  MongoDB:
    autostart: true
    password: ''

webserver:
  ApacheHTTPd:
    autostart: true

  NginX:
    autostart: false